language: node_js
node_js:
- 14
deploy:
  on:
    branch: main
  provider: script
  skip_cleanup: true
  before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  script: yarn lerna publish from-package --yes
