language: node_js
node_js:
- 14
deploy:
  on:
    branch: main
  provider: npm
  skip_cleanup: true
  email:
    secure: dI/YOUOz/5ZIKTATlguRC21OZXIFErhkJP2On9/qwJYMM/ctNkh4ChbblP5iaEkkMDeop3RCCTT3qzgClenPpUbscXPEmhMQpp/wBNrBJTTqZRXQeOYePwY42+dv/vRtTHHyUV2z0f260TIXwY0eXQYCFdgZN5TcUrOq6b9VbGE/vaxi9wWvAFdRgS5ZWsbLRJYRR1a/hh60gcyTfzzSpVB2t+YE3UrAQcV398H3k8iWjkyFGWIrVCTgRCGGroo8BobmrAQh9Nj3OrLfjdCjj3bzSBdOQn+tYocirPD3HvkHbb2qXI/lHS6nyeFDfJa3qMmt2nD8+LHFzdLdKy99lnGwmk6ujmAh2fymEXqwdpWq1T449GxxSdfbqNK7T8FpyPcbSZ2MN2wiPM98yAe7cjA6SDNA4syzPTffy58+D1UF1e9KII+4NlWG0Y9Vh+xVyTccj8IhqZrSfq8cIC3t7nlm3KRE6rln6ZXrjan/1K7JgqOpiJRLHdXzzUXORLWUAk+HC0ezmKwdXvhovGgYRHZ9k06XOazh+HfZR+KznVgMpQO4DsRH5SLG+KLEOxui+AknBrAAm2TYG4o1d8sqDMHZXkb88/zwRr/YemeY4cLhiNHDi6WxYKsvKqTzopjklx7Jr8kvuoeSTc3ug4cqflxFUYYPLeRnPJvWTyKTpak=
  api_key:
    secure: VDDr/eeLToBl5vN8o4XEsPAjSmyPmQUzSYPAAmmIjD1KsnWMGYjN1Z9ZcRMG7gtRem7gZNmfwVL8C31HR9rDWUSm8WFjSBI684H6l7fel3B77HrzKlLaSs5VIQ8E3OTvN+mjMvfCy84n3m8UTWNqX9sBGXy3uKvI81NR1A30Z5BLdeWPR20C+MH5Yk56l+1j5BOKoLnG8SkVlduvn/zuge6nFXHOuyXNImX1/YFG4oxLh8MIHfxYDoUWgS1V2ShKbQTFIZby1f54wrl4snFCbLfzNxBWlpS65mp/V3QT4V9Cd7/nkF8WtUvFp5RtC1u6fflr24OIbwKvm4TVx3EYLbIMzt+FkhMDb78So+i/h93UfGAWDc2t6cu9IweMaSFKeyre4qfoXFx6KKKXlSLDOg3MiJVuJ5+1AwuS2RHhz/gz5/Bba+RJOBAY2hAsf22pQlRpqfgt+gwq9IeTKAt4YGHIVl9ycB0cWAcuw7AjvZpenfkqOMT3bvzjzJk+0vEycwB+lP3KC10KMWvUF873zp0gFFRn5RqRWUDTa1Yi3PZqryQqNkkbblmoWqI1X5ZIeqhbsBKRAzYE8Ojkr9a+aClbQII21acZdXGZd4mOzTinV0p/00KiVI8qn4IotAPYcnjQ/WLJ32rB0AFM+r/s80GPPXvjnwpqhj4QlbUSS/c=
