name: build-test-deploy-main
on: 
  push:
    branches:
    - main
jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn test
      - run: cp .npmrc-publish ~/.npmrc
      - run: yarn lerna publish from-package --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USER: ${{ secrets.NPM_USER }}