name: build-test-pull-requests
on: 
  pull_request:
    branches:
    - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build and Unit Test
        id: buidtest
        run: npm ci
        run: npm run build
        run: npm run test
      - name: Functional Test
        id: functionaltest
        run: npm run test-examples