name: build-test-pull-requests
on: 
  pull_request:
    branches:
    - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        id: installdeps
        run: npm ci
      - name: Build Projects
        id: buildproj
        run: npm run build
      - name: Check Circular Refs
        id: circularrefs
        run: npx dpdm -T --warning false **/index.ts
      - name: Run Unit Tests with Coverage
        id: unittestcov
        run: npm run coverage