name: deploy-pages-main
on: 
  push:
    branches:
    - main
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        id: installdeps
        run: npm ci
      - name: Build HTML docs
        id: builddocs
        run: npm run docs
      - uses: actions/deploy-pages@v4