name: run-test-examples
on: workflow_dispatch
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        id: installdeps
        run: npm ci
      - name: Run Example Test Projects
        # only run functional tests on internal PRs
        id: exampleprojecttests
        run: npm run test:examples
        env:
          browserstack_user: ${{ secrets.BROWSERSTACK_USER }}
          browserstack_key: ${{ secrets.BROWSERSTACK_KEY }}